all: day01 day02 day03 day04 day05 day06 day07 day08 day09 day10 day11 day12 day13 day14

day01: day01.c
	gcc day01.c -o day01

day02: day02.c
	gcc day02.c -o day02

day03: day03.c
	gcc day03.c -o day03

day04: day04.c
	gcc day04.c -o day04

day05: day05.c
	gcc day05.c -o day05

day06: day06.c
	gcc day06.c -o day06

day07: day07.c
	gcc day07.c -o day07

day08: day08.c
	gcc day08.c -o day08

day09: day09.c
	gcc day09.c -o day09

day10: day10.c
	gcc day10.c -o day10

day11: day11.c
	gcc day11.c -o day11

day12: day12.c
	gcc day12.c -o day12

day13: day13.c
	gcc day13.c -o day13

day14: day14.c
	gcc day14.c -o day14

clean:
	rm -f day01 day02 day03 day04 day05 day06 day07 day08 day09 day10 day11 day12 day13 day14