all: day01 day02 day03 day04 day05 day06 day07

day01: day01.c
	gcc day01.c -o day01

day02: day02.c
	gcc day02.c -o day02

day03: day03.c
	gcc day03.c -o day03

day04: day04.c
	gcc day04.c -o day04

day05: day05.c
	gcc day05.c -o day05

day06: day06.c
	gcc day06.c -o day06

day07: day07.c
	gcc day07.c -o day07

clean:
	rm -f day01 day02 day03 day04 day05 day06 day07